version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node --version
            - run: cd api && npm install
            - run: cd api && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test-api