version: 2.1
orbs:
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2
  cypress: cypress-io/cypress@1
jobs:
  build-and-test-ui:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ui && npm install
            - run: cd ui && CI=true npm test
      - slack/status:
          fail_only: true
  build-and-test-api:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd api && npm install
            - run: cd api && npm test
      - slack/status:
          fail_only: true
workflows:
    build-and-test:
      jobs:
        - build-and-test-ui
        - build-and-test-api
        - cypress/run:
            working_directory: ui
            command: npm run-script cy:ci
            no-workspace: true