const STOP_WORDS= {
    /* English */
    "1": /\b(a|about|above|after|again|against|all|am|an|and|any|are|aren't|as|at|be|because|been|before|being|below|between|both|but|by|can't|cannot|could|couldn't|did|didn't|do|does|doesn't|doing|don't|down|during|each|few|for|from|further|get|had|hadn't|has|hasn't|have|haven't|having|he|he'd|he'll|he's|her|here|here's|hers|herself|him|himself|his|how|how's|i|i'd|i'll|i'm|i've|if|in|into|is|isn't|it|it's|its|itself|let's|like|lot|may|maybe|me|more|most|much|mustn't|my|myself|no|nor|not|of|off|on|once|only|or|other|ought|our|ours|ourselves|out|over|own|same|shan't|she|she'd|she'll|she's|should|shouldn't|so|some|such|than|that|that's|the|their|theirs|them|themselves|then|there|there's|these|they|they'd|they'll|they're|they've|this|those|through|to|too|under|until|up|very|was|wasn't|we|we'd|we'll|we're|we've|were|weren't|what|what's|when|when's|where|where's|which|while|who|who's|whom|why|why's|with|won't|would|wouldn't|you|you'd|you'll|you're|you've|your|yours|yourself|yourselves)\b/ig,
    /* French  */
    "2": /\b(alors|au|aucuns|aussi|autre|avant|avec|avoir|bon|car|ce|cela|ces|ceux|chaque|ci|comme|comment|dans|des|du|dedans|dehors|depuis|deux|devrait|doit|donc|dos|droite|début|elle|elles|en|encore|essai|est|et|eu|fait|faites|fois|font|force|haut|hors|ici|il|ils|je|juste|la|le|les|leur|là|ma|maintenant|mais|mes|mine|moins|mon|mot|même|ni|nommés|notre|nous|nouveaux|ou|où|par|parce|parole|pas|personnes|peut|peu|pièce|plupart|pour|pourquoi|quand|que|quel|quelle|quelles|quels|qui|sa|sans|ses|seulement|si|sien|son|sont|sous|soyez|sujet|sur|ta|tandis|tellement|tels|tes|ton|tous|tout|trop|très|tu|valeur|voie|voient|vont|votre|vous|vu|ça|étaient|état|étions|été|être)\b/ig,
    /* German  */
    "3": /\b(aber|als|am|an|auch|auf|aus|bei|bin|bis|bist|da|dadurch|daher|darum|das|daß|dass|dein|deine|dem|den|der|des|dessen|deshalb|die|dies|dieser|dieses|doch|dort|du|durch|ein|eine|einem|einen|einer|eines|er|es|euer|eure|für|hatte|hatten|hattest|hattet|hier|hinter|ich|ihr|ihre|im|in|ist|ja|jede|jedem|jeden|jeder|jedes|jener|jenes|jetzt|kann|kannst|können|könnt|machen|mein|meine|mit|muß|mußt|musst|müssen|müßt|nach|nachdem|nein|nicht|nun|oder|seid|sein|seine|sich|sie|sind|soll|sollen|sollst|sollt|sonst|soweit|sowie|und|unser|unsere|unter|vom|von|vor|wann|warum|was|weiter|weitere|wenn|wer|werde|werden|werdet|weshalb|wie|wieder|wieso|wir|wird|wirst|wo|woher|wohin|zu|zum|zur|über)\b/ig,
    /* Spanish  */
    "4": /\b(un|una|unas|unos|uno|sobre|todo|también|tras|otro|algún|alguno|alguna|algunos|algunas|ser|es|soy|eres|somos|sois|estoy|esta|estamos|estais|estan|como|en|para|atras|porque|por qué|estado|estaba|ante|antes|siendo|ambos|pero|por|poder|puede|puedo|podemos|podeis|pueden|fui|fue|fuimos|fueron|hacer|hago|hace|hacemos|haceis|hacen|cada|fin|incluso|primero|desde|conseguir|consigo|consigue|consigues|conseguimos|consiguen|ir|voy|va|vamos|vais|van|vaya|gueno|ha|tener|tengo|tiene|tenemos|teneis|tienen|el|la|lo|las|los|su|aqui|mio|tuyo|ellos|ellas|nos|nosotros|vosotros|vosotras|si|dentro|solo|solamente|saber|sabes|sabe|sabemos|sabeis|saben|ultimo|largo|bastante|haces|muchos|aquellos|aquellas|sus|entonces|tiempo|verdad|verdadero|verdadera|cierto|ciertos|cierta|ciertas|intentar|intento|intenta|intentas|intentamos|intentais|intentan|dos|bajo|arriba|encima|usar|uso|usas|usa|usamos|usais|usan|emplear|empleo|empleas|emplean|ampleamos|empleais|valor|muy|era|eras|eramos|eran|modo|bien|cual|cuando|donde|mientras|quien|con|entre|sin|trabajo|trabajar|trabajas|trabaja|trabajamos|trabajais|trabajan|podria|podrias|podriamos|podrian|podriais|yo|aquel)\b/ig,
    /* Arabic  */
    "5": /\b(فى|في|كل|لم|لن|له|من|هو|هي|قوة|كما|لها|منذ|وقد|ولا|نفسه|لقاء|مقابل|هناك|وقال|وكان|نهاية|وقالت|وكانت|للامم|فيه|كلم|لكن|وفي|وقف|ولم|ومن|وهو|وهي|يوم|فيها|منها|مليار|لوكالة|يكون|يمكن|مليون|حيث|اكد|الا|اما|امس|السابق|التى|التي|اكثر|ايار|ايضا|ثلاثة|الذاتي|الاخيرة|الثاني|الثانية|الذى|الذي|الان|امام|ايام|خلال|حوالى|الذين|الاول|الاولى|بين|ذلك|دون|حول|حين|الف|الى|انه|اول|ضمن|انها|جميع|الماضي|الوقت|المقبل|اليوم|ـ|ف|و|و6|قد|لا|ما|مع|مساء|هذا|واحد|واضاف|واضافت|فان|قبل|قال|كان|لدى|نحو|هذه|وان|واكد|كانت|واوضح|مايو|ب|ا|أ|،|عشر|عدد|عدة|عشرة|عدم|عام|عاما|عن|عند|عندما|على|عليه|عليها|زيارة|سنة|سنوات|تم|ضد|بعد|بعض|اعادة|اعلنت|بسبب|حتى|اذا|احد|اثر|برس|باسم|غدا|شخصا|صباح|اطار|اربعة|اخرى|بان|اجل|غير|بشكل|حاليا|بن|به|ثم|اف|ان|او|اي|بها|صفر)\b/ig,
    /* Chinese*/
    "6": /\b(的|一|不|在|人|有|是|为|以|于|上|他|而|后|之|来|及|了|因|下|可|到|由|这|与|也|此|但|并|个|其|已|无|小|我|们|起|最|再|今|去|好|只|又|或|很|亦|某|把|那|你|乃|它|吧|被|比|别|趁|当|从|到|得|打|凡|儿|尔|该|各|给|跟|和|何|还|即|几|既|看|据|距|靠|啦|了|另|么|每|们|嘛|拿|哪|那|您|凭|且|却|让|仍|啥|如|若|使|谁|虽|随|同|所|她|哇|嗡|往|哪|些|向|沿|哟|用|于|咱|则|怎|曾|至|致|着|诸|自)\b/ig,
    /* Japanese */
    "7": /\b(これ|それ|あれ|この|その|あの|ここ|そこ|あそこ|こちら|どこ|だれ|なに|なん|何|私|貴方|貴方方|我々|私達|あの人|あのかた|彼女|彼|です|あります|おります|います|は|が|の|に|を|で|え|から|まで|より|も|どの|と|し|それで|しかし)\b/ig,
    /* Hebrew*/
    "8": /\b(אני|את|אתה|אנחנו|אתן|אתם|הם|הן|היא|הוא|שלי|שלו|שלך|שלה|שלנו|שלכם|שלכן|שלהם|שלהן|לי|לו|לה|לנו|לכם|לכן|להם|להן|אותה|אותו|זה|זאת|אלה|אלו|תחת|מתחת|מעל|בין|עם|עד|נגר|על|אל|מול|של|אצל|כמו|אחר|אותו|בלי|לפני|אחרי|מאחורי|עלי|עליו|עליה|עליך|עלינו|עליכם|לעיכן|עליהם|עליהן|כל|כולם|כולן|כך|ככה|כזה|זה|זות|אותי|אותה|אותם|אותך|אותו|אותן|אותנו|ואת|את|אתכם|אתכן|איתי|איתו|איתך|איתה|איתם|איתן|איתנו|איתכם|איתכן|יהיה|תהיה|היתי|היתה|היה|להיות|עצמי|עצמו|עצמה|עצמם|עצמן|עצמנו|עצמהם|עצמהן|מי|מה|איפה|היכן|במקום שבו|אם|לאן|למקום שבו|מקום בו|איזה|מהיכן|איך|כיצד|באיזו מידה|מתי|בשעה ש|כאשר|כש|למרות|לפני|אחרי|מאיזו סיבה|הסיבה שבגללה|למה|מדוע|לאיזו תכלית|כי|יש|אין|אך|מנין|מאין|מאיפה|יכל|יכלה|יכלו|יכול|יכולה|יכולים|יכולות|יוכלו|יוכל|מסוגל|לא|רק|אולי|אין|לאו|אי|כלל|נגד|אם|עם|אל|אלה|אלו|אף|על|מעל|מתחת|מצד|בשביל|לבין|באמצע|בתוך|דרך|מבעד|באמצעות|למעלה|למטה|מחוץ|מן|לעבר|מכאן|כאן|הנה|הרי|פה|שם|אך|ברם|שוב|אבל|מבלי|בלי|מלבד|רק|בגלל|מכיוון|עד|אשר|ואילו|למרות|אס|כמו|כפי|אז|אחרי|כן|לכן|לפיכך|מאד|עז|מעט|מעטים|במידה|שוב|יותר|מדי|גם|כן|נו|אחר|אחרת|אחרים|אחרות|אשר|או)\b/ig,
    /* Hindi*/
    "9": /\b(के|का|एक|में|की|है|यह|और|से|हैं|को|पर|इस|होता|कि|जो|कर|मे|गया|करने|किया|लिये|अपने|ने|बनी|नहीं|तो|ही|या|एवं|दिया|हो|इसका|था|द्वारा|हुआ|तक|साथ|करना|वाले|बाद|लिए|आप|कुछ|सकते|किसी|ये|इसके|सबसे|इसमें|थे|दो|होने|वह|वे|करते|बहुत|कहा|वर्ग|कई|करें|होती|अपनी|उनके|थी|यदि|हुई|जा|ना|इसे|कहते|जब|होते|कोई|हुए|व|न|अभी|जैसे|सभी|करता|उनकी|तरह|उस|आदि|कुल|एस|रहा|इसकी|सकता|रहे|उनका|इसी|रखें|अपना|पे|उसके)\b/ig,
    /* Russian*/
    "10": /\b(а|е|и|ж|м|о|на|не|ни|об|но|он|мне|мои|мож|она|они|оно|мной|много|многочисленное|многочисленная|многочисленные|многочисленный|мною|мой|мог|могут|можно|может|можхо|мор|моя|моё|мочь|над|нее|оба|нам|нем|нами|ними|мимо|немного|одной|одного|менее|однажды|однако|меня|нему|меньше|ней|наверху|него|ниже|мало|надо|один|одиннадцать|одиннадцатый|назад|наиболее|недавно|миллионов|недалеко|между|низко|меля|нельзя|нибудь|непрерывно|наконец|никогда|никуда|нас|наш|нет|нею|неё|них|мира|наша|наше|наши|ничего|начала|нередко|несколько|обычно|опять|около|мы|ну|нх|от|отовсюду|особенно|нужно|очень|отсюда|в|во|вон|вниз|внизу|вокруг|вот|восемнадцать|восемнадцатый|восемь|восьмой|вверх|вам|вами|важное|важная|важные|важный|вдали|везде|ведь|вас|ваш|ваша|ваше|ваши|впрочем|весь|вдруг|вы|все|второй|всем|всеми|времени|время|всему|всего|всегда|всех|всею|всю|вся|всё|всюду|г|год|говорил|говорит|года|году|где|да|ее|за|из|ли|же|им|до|по|ими|под|иногда|довольно|именно|долго|позже|более|должно|пожалуйста|значит|иметь|больше|пока|ему|имя|пор|пора|потом|потому|после|почему|почти|посреди|ей|два|две|двенадцать|двенадцатый|двадцать|двадцатый|двух|его|дел|или|без|день|занят|занята|занято|заняты|действительно|давно|девятнадцать|девятнадцатый|девять|девятый|даже|алло|жизнь|далеко|близко|здесь|дальше|для|лет|зато|даром|первый|перед|затем|зачем|лишь|десять|десятый|ею|её|их|бы|еще|при|был|про|процентов|против|просто|бывает|бывь|если|люди|была|были|было|будем|будет|будете|будешь|прекрасно|буду|будь|будто|будут|ещё|пятнадцать|пятнадцатый|друго|другое|другой|другие|другая|других|есть|пять|быть|лучше|пятый|к|ком|конечно|кому|кого|когда|которой|которого|которая|которые|который|которых|кем|каждое|каждая|каждые|каждый|кажется|как|какой|какая|кто|кроме|куда|кругом|с|т|у|я|та|те|уж|со|то|том|снова|тому|совсем|того|тогда|тоже|собой|тобой|собою|тобою|сначала|только|уметь|тот|тою|хорошо|хотеть|хочешь|хоть|хотя|свое|свои|твой|своей|своего|своих|свою|твоя|твоё|раз|уже|сам|там|тем|чем|сама|сами|теми|само|рано|самом|самому|самой|самого|семнадцать|семнадцатый|самим|самими|самих|саму|семь|чему|раньше|сейчас|чего|сегодня|себе|тебе|сеаой|человек|разве|теперь|себя|тебя|седьмой|спасибо|слишком|так|такое|такой|такие|также|такая|сих|тех|чаще|четвертый|через|часто|шестой|шестнадцать|шестнадцатый|шесть|четыре|четырнадцать|четырнадцатый|сколько|сказал|сказала|сказать|ту|ты|три|эта|эти|что|это|чтоб|этом|этому|этой|этого|чтобы|этот|стал|туда|этим|этими|рядом|тринадцать|тринадцатый|этих|третий|тут|эту|суть|чуть|тыся)\b/ig
};

const removeStopWords = (language, str) => str.replace(STOP_WORDS[language || '1'], '');

module.exports = { removeStopWords };